  ci[m
  development[m
* [32mfeature/Persistence[m
  feature/shop-inventory[m
  master[m
  [31mremotes/origin/BuyAndSell[m
  [31mremotes/origin/HEAD[m -> origin/master
  [31mremotes/origin/ThePark[m
  [31mremotes/origin/ci[m
  [31mremotes/origin/development[m
  [31mremotes/origin/development-keybindings[m
  [31mremotes/origin/development-mainmenu[m
  [31mremotes/origin/development-tourists[m
  [31mremotes/origin/feature/Persistence[m
  [31mremotes/origin/feature/add-license[m
  [31mremotes/origin/feature/animal[m
  [31mremotes/origin/feature/building[m
  [31mremotes/origin/feature/camera[m
  [31mremotes/origin/feature/camera-cursor-idd[m
  [31mremotes/origin/feature/challenge[m
  [31mremotes/origin/feature/cursor[m
  [31mremotes/origin/feature/global-input-manager[m
  [31mremotes/origin/feature/input-device-detector[m
  [31mremotes/origin/feature/level[m
  [31mremotes/origin/feature/mainmenu[m
  [31mremotes/origin/feature/mainmenu-controls[m
  [31mremotes/origin/feature/npc[m
  [31mremotes/origin/feature/pause-menu[m
  [31mremotes/origin/feature/shop[m
  [31mremotes/origin/feature/shop-inventory[m
  [31mremotes/origin/feature/tourist[m
  [31mremotes/origin/feature/vehicle[m
  [31mremotes/origin/feature/virtual-cursor[m
  [31mremotes/origin/master[m
